### PR TITLE
Repair warp conversion

### PR DESCRIPTION
**Pull request by pydsigner**
Actually do some math instead of pulling magic numbers out of the code's orifices

### CODE REVIEW

**Comment by mekolat** [comment]
mmmmm orifices

**Comment by mekolat** [comment]
I can still see a problem: if `self.base + self.name_unique > 23` we need to also truncate that `self.base`

**Comment by wushin** [comment]
warp names are only used by client. warps are only triggered on touch. one could right the random generator into the Warp NPC script parse. Ideally it would be nice to just have it read the maps directly.

**Comment by pydsigner** [comment]
Diking out the warp names entirely seems the smartest thing to me.

**Pull request closed without merging**
